# Generated by Django 3.2.5 on 2021-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop_app', '0003_auto_20210725_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cake_shop_app.Product'),
        ),
    ]
