# Generated by Django 3.2.5 on 2021-07-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop_app', '0004_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
