# Generated by Django 3.2.5 on 2021-07-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop_app', '0009_rename_items_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
    ]
