# Generated by Django 3.2.5 on 2021-07-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop_app', '0010_auto_20210727_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cake_shop_app.OrderItem'),
        ),
    ]
