# Generated by Django 3.2.5 on 2021-08-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
